# PANDAS

Izgrađen na temelju NumPy library-ja za brzu analizu podataka, čišćenje podataka, pripremu tj. preprocessing.
U pozadini, pandas koristi NumPy nizove za pohranu podataka, NumPy funkcije kod numeričkih izraza itd.

Osnovne funkcije:


*   import i export podataka u razl. formatima (CSV, txt, xlsx i sl.)
*   statistika

*   indeksiranje, sortiranje
*   čišćenje podataka, filtriranje, grupiranje

*   vizualizacija podataka








In [1]:
import pandas as pd
import numpy as np

## Series

In [2]:
my_list = [10, 20, 30]
my_list

[10, 20, 30]

In [3]:
arr = np.array(my_list)
arr

array([10, 20, 30])

In [4]:
# ndim
# dimenzija array-a (niza)

arr.ndim

1

In [5]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [6]:
ind = ['a','b','c']

pd.Series(data=my_list, index=ind, name='stupac')

a    10
b    20
c    30
Name: stupac, dtype: int64

In [7]:
d = {'a':1, 'b':2}
d

{'a': 1, 'b': 2}

In [8]:
pd.Series(data=d, name='stupac')

a    1
b    2
Name: stupac, dtype: int64

In [9]:
tab1 = pd.Series(data=[1,2,3,4], index=['A','B','C','D'], name='data')
tab1

A    1
B    2
C    3
D    4
Name: data, dtype: int64

In [10]:
tab1[0]

<ipython-input-10-69023866f8d8>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  tab1[0]


1

In [11]:
tab1['A']

1

In [12]:
# loc -> labels
# iloc -> locations

tab1.iloc[0]

1

In [13]:
tab1.loc['A']

1

In [14]:
# zbrajanje Series-a

tab2 = pd.Series(data=[2,4,5,6], index=['A','E','C','F'])
tab2

A    2
E    4
C    5
F    6
dtype: int64

In [15]:
tab1 + tab2

A    3.0
B    NaN
C    8.0
D    NaN
E    NaN
F    NaN
dtype: float64

## DataFrame

In [16]:
# numpy funkcija randn

np.random.randn(5,4)

# stvaramo matricu 5x4 (2D array)

array([[-1.49252255,  0.04298919, -1.43562265, -0.03991735],
       [-0.92315105,  0.5932277 ,  0.91981995,  1.72292056],
       [ 1.05559635, -0.07632145,  0.10646087, -0.1735221 ],
       [-0.75932694,  0.91501737, -1.09094521, -0.81570076],
       [-0.94669659,  0.77074381,  0.46070017, -0.38511021]])

In [17]:
# drugi način

from numpy.random import randn

In [19]:
randn(5,4)

array([[ 1.01117758,  0.05325903,  0.02833031, -0.49493871],
       [ 0.19263844, -0.31285885,  2.63944728,  0.68146593],
       [-0.27268495, -0.43892398, -0.37328648, -1.80047694],
       [-0.99812752, -1.46062304, -1.99683885,  0.06176969],
       [ 0.67146855,  0.1886956 , -0.56701765,  1.21711403]])

In [20]:
df = pd.DataFrame(data=randn(5,4), index=['A', 'B','C','D','E'], columns=['W','X','Y','Z'])
df

W         X         Y         Z
A  0.345445  0.004598  0.750263 -1.060920
B  0.665245  0.678554  0.595346 -1.366467
C -0.947768 -0.550256  0.077649 -1.074123
D  0.685917 -0.652251  0.218359  0.718240
E  0.815942 -0.272617 -0.682130  0.702779

In [21]:
df.columns = [1,2,3,4]
df

1         2         3         4
A  0.345445  0.004598  0.750263 -1.060920
B  0.665245  0.678554  0.595346 -1.366467
C -0.947768 -0.550256  0.077649 -1.074123
D  0.685917 -0.652251  0.218359  0.718240
E  0.815942 -0.272617 -0.682130  0.702779

In [22]:
type(df.loc['A'])

pandas.core.series.Series

In [23]:
type(df)

pandas.core.frame.DataFrame

In [24]:
df.iloc[:,[0,2]]

1         3
A  0.345445  0.750263
B  0.665245  0.595346
C -0.947768  0.077649
D  0.685917  0.218359
E  0.815942 -0.682130

In [25]:
df.loc[:,[1,3]]

1         3
A  0.345445  0.750263
B  0.665245  0.595346
C -0.947768  0.077649
D  0.685917  0.218359
E  0.815942 -0.682130

In [26]:
df.iloc[2:4,2:]

3         4
C  0.077649 -1.074123
D  0.218359  0.718240

In [27]:
df[[3,4]].loc[['C','D']]

3         4
C  0.077649 -1.074123
D  0.218359  0.718240

In [28]:
df.columns = ['W','X','Y','Z']

In [29]:
a = df[['W','X']].loc['B']
a

W    0.665245
X    0.678554
Name: B, dtype: float64

In [30]:
type(a)

pandas.core.series.Series

In [31]:
pd.DataFrame(data=a)

B
W  0.665245
X  0.678554

In [32]:
df

W         X         Y         Z
A  0.345445  0.004598  0.750263 -1.060920
B  0.665245  0.678554  0.595346 -1.366467
C -0.947768 -0.550256  0.077649 -1.074123
D  0.685917 -0.652251  0.218359  0.718240
E  0.815942 -0.272617 -0.682130  0.702779

## Statistika

In [33]:
# statistika
# loc i iloc -> index stupac (A,B,C,D,E)

df.loc['C'].std()

0.518068700525398

In [35]:
# [] -> index red (W,X,Y,Z)

df['X'].var()

0.2843862842365173

In [37]:
round(df.loc['C'].std(), 4)

0.5181

In [38]:
df['W'].max() - df['Z'].min()

2.1824085864351876

In [39]:
df['X'].std() > df.loc['D'].std()

False

## Kreiramo novi stupac

In [40]:
df['WminY'] = df['W'] - df['Y']

In [41]:
df

W         X         Y         Z     WminY
A  0.345445  0.004598  0.750263 -1.060920 -0.404818
B  0.665245  0.678554  0.595346 -1.366467  0.069899
C -0.947768 -0.550256  0.077649 -1.074123 -1.025417
D  0.685917 -0.652251  0.218359  0.718240  0.467558
E  0.815942 -0.272617 -0.682130  0.702779  1.498072

In [42]:
df['logX'] = np.log10(df['X'])
df

/usr/local/lib/python3.11/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: invalid value encountered in log10
  result = getattr(ufunc, method)(*inputs, **kwargs)


W         X         Y         Z     WminY      logX
A  0.345445  0.004598  0.750263 -1.060920 -0.404818 -2.337386
B  0.665245  0.678554  0.595346 -1.366467  0.069899 -0.168416
C -0.947768 -0.550256  0.077649 -1.074123 -1.025417       NaN
D  0.685917 -0.652251  0.218359  0.718240  0.467558       NaN
E  0.815942 -0.272617 -0.682130  0.702779  1.498072       NaN

In [43]:
def ph(c):
  return -np.log10(c)

In [44]:
# apply

df['X'].apply(ph)

<ipython-input-43-8db3b9fa567e>:2: RuntimeWarning: invalid value encountered in log10
  return -np.log10(c)


A    2.337386
B    0.168416
C         NaN
D         NaN
E         NaN
Name: X, dtype: float64

In [45]:
# lambda - anonimna (bezimena) funkcija
# lambda argument(i): izraz

df['Y'].apply(lambda x: -np.log10(x))

<ipython-input-45-b260faf39855>:4: RuntimeWarning: invalid value encountered in log10
  df['Y'].apply(lambda x: -np.log10(x))


A    0.124786
B    0.225231
C    1.109866
D    0.660829
E         NaN
Name: Y, dtype: float64

In [46]:
def above_LOD(x):

  if x > 0.01:
    return 'iznad LOD'
  else:
    return 'XXX'

In [47]:
# applymap

df.applymap(above_LOD)

<ipython-input-47-498cf450487f>:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(above_LOD)


W          X          Y          Z      WminY logX
A  iznad LOD        XXX  iznad LOD        XXX        XXX  XXX
B  iznad LOD  iznad LOD  iznad LOD        XXX  iznad LOD  XXX
C        XXX        XXX  iznad LOD        XXX        XXX  XXX
D  iznad LOD        XXX  iznad LOD  iznad LOD  iznad LOD  XXX
E  iznad LOD        XXX        XXX  iznad LOD  iznad LOD  XXX

In [48]:
# 1

df.applymap(lambda x: 2*x + 100)

<ipython-input-48-1724e909abcd>:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(lambda x: 2*x + 100)


W           X           Y           Z       WminY       logX
A  100.690890  100.009197  101.500526   97.878160   99.190364  95.325227
B  101.330489  101.357107  101.190692   97.267067  100.139798  99.663168
C   98.104464   98.899488  100.155297   97.851753   97.949166        NaN
D  101.371834   98.695498  100.436718  101.436481  100.935116        NaN
E  101.631884   99.454766   98.635739  101.405557  102.996145        NaN

In [49]:
# 2

def fun(x):
  return 2*x+100

df.applymap(fun)

<ipython-input-49-88e324544ae4>:6: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(fun)


W           X           Y           Z       WminY       logX
A  100.690890  100.009197  101.500526   97.878160   99.190364  95.325227
B  101.330489  101.357107  101.190692   97.267067  100.139798  99.663168
C   98.104464   98.899488  100.155297   97.851753   97.949166        NaN
D  101.371834   98.695498  100.436718  101.436481  100.935116        NaN
E  101.631884   99.454766   98.635739  101.405557  102.996145        NaN

In [50]:
df

W         X         Y         Z     WminY      logX
A  0.345445  0.004598  0.750263 -1.060920 -0.404818 -2.337386
B  0.665245  0.678554  0.595346 -1.366467  0.069899 -0.168416
C -0.947768 -0.550256  0.077649 -1.074123 -1.025417       NaN
D  0.685917 -0.652251  0.218359  0.718240  0.467558       NaN
E  0.815942 -0.272617 -0.682130  0.702779  1.498072       NaN

In [52]:
df['aboveLOD'] = df['X'].apply(lambda x: x if x > 0.01 else 0.0001)
df

W         X         Y         Z     WminY      logX  aboveLOD
A  0.345445  0.004598  0.750263 -1.060920 -0.404818 -2.337386  0.000100
B  0.665245  0.678554  0.595346 -1.366467  0.069899 -0.168416  0.678554
C -0.947768 -0.550256  0.077649 -1.074123 -1.025417       NaN  0.000100
D  0.685917 -0.652251  0.218359  0.718240  0.467558       NaN  0.000100
E  0.815942 -0.272617 -0.682130  0.702779  1.498072       NaN  0.000100

In [53]:
df['aboveLOD'] = df['X'].apply(lambda x: x if x >= 0.001 else '<LOD')
df

W         X         Y         Z     WminY      logX  aboveLOD
A  0.345445  0.004598  0.750263 -1.060920 -0.404818 -2.337386  0.004598
B  0.665245  0.678554  0.595346 -1.366467  0.069899 -0.168416  0.678554
C -0.947768 -0.550256  0.077649 -1.074123 -1.025417       NaN      <LOD
D  0.685917 -0.652251  0.218359  0.718240  0.467558       NaN      <LOD
E  0.815942 -0.272617 -0.682130  0.702779  1.498072       NaN      <LOD

## Izbacivanje kolone

In [56]:
# axis = 1 - odnosi se na stupce

df = df.drop(['aboveLOD'], axis=1)
df

KeyError: "['aboveLOD'] not found in axis"

In [57]:
df

W         X         Y         Z     WminY      logX
A  0.345445  0.004598  0.750263 -1.060920 -0.404818 -2.337386
B  0.665245  0.678554  0.595346 -1.366467  0.069899 -0.168416
C -0.947768 -0.550256  0.077649 -1.074123 -1.025417       NaN
D  0.685917 -0.652251  0.218359  0.718240  0.467558       NaN
E  0.815942 -0.272617 -0.682130  0.702779  1.498072       NaN

In [58]:
df.drop('B', axis=0)

W         X         Y         Z     WminY      logX
A  0.345445  0.004598  0.750263 -1.060920 -0.404818 -2.337386
C -0.947768 -0.550256  0.077649 -1.074123 -1.025417       NaN
D  0.685917 -0.652251  0.218359  0.718240  0.467558       NaN
E  0.815942 -0.272617 -0.682130  0.702779  1.498072       NaN

In [61]:
df

W         X         Y         Z     WminY      logX
A  0.345445  0.004598  0.750263 -1.060920 -0.404818 -2.337386
B  0.665245  0.678554  0.595346 -1.366467  0.069899 -0.168416
C -0.947768 -0.550256  0.077649 -1.074123 -1.025417       NaN
D  0.685917 -0.652251  0.218359  0.718240  0.467558       NaN
E  0.815942 -0.272617 -0.682130  0.702779  1.498072       NaN

In [64]:
df

W         X         Y         Z     WminY      logX
A  0.345445  0.004598  0.750263 -1.060920 -0.404818 -2.337386
B  0.665245  0.678554  0.595346 -1.366467  0.069899 -0.168416
C -0.947768 -0.550256  0.077649 -1.074123 -1.025417       NaN
D  0.685917 -0.652251  0.218359  0.718240  0.467558       NaN
E  0.815942 -0.272617 -0.682130  0.702779  1.498072       NaN

In [62]:
df.drop(['WminY','logX'], axis=1, inplace=True)

W         X         Y         Z
A  0.345445  0.004598  0.750263 -1.060920
B  0.665245  0.678554  0.595346 -1.366467
C -0.947768 -0.550256  0.077649 -1.074123
D  0.685917 -0.652251  0.218359  0.718240
E  0.815942 -0.272617 -0.682130  0.702779

In [63]:
df

W         X         Y         Z     WminY      logX
A  0.345445  0.004598  0.750263 -1.060920 -0.404818 -2.337386
B  0.665245  0.678554  0.595346 -1.366467  0.069899 -0.168416
C -0.947768 -0.550256  0.077649 -1.074123 -1.025417       NaN
D  0.685917 -0.652251  0.218359  0.718240  0.467558       NaN
E  0.815942 -0.272617 -0.682130  0.702779  1.498072       NaN

In [65]:
df.dtypes

W        float64
X        float64
Y        float64
Z        float64
WminY    float64
logX     float64
dtype: object

In [67]:
df.drop(['logX'], axis=1, inplace=True)

In [68]:
df_int = df.astype(int)
df_int

W  X  Y  Z  WminY
A  0  0  0 -1      0
B  0  0  0 -1      0
C  0  0  0 -1     -1
D  0  0  0  0      0
E  0  0  0  0      1

## Boolean

In [69]:
# nije jednako !=

df[['W','X','Y']] != 0

W     X     Y
A  True  True  True
B  True  True  True
C  True  True  True
D  True  True  True
E  True  True  True

In [71]:
df_b = df[['W','X','Y']] > 0
df_b

W      X      Y
A   True   True   True
B   True   True   True
C  False  False   True
D   True  False   True
E   True  False  False

In [74]:
df[df_b].dropna(how='all', axis=0).dropna(how='all', axis=1).dropna(how='any', axis=0).dropna(how='any', axis=1)

W         X         Y
A  0.345445  0.004598  0.750263
B  0.665245  0.678554  0.595346

In [75]:
df = pd.DataFrame(data=randn(5,4),
                  index=['A','B','C','D','E'],
                  columns=['W','X','Y','Z'])
df

W         X         Y         Z
A  0.432646 -1.293831  0.777318  2.366005
B  0.395894  1.835238  0.112152 -1.323530
C  0.213568  1.551675  2.147714 -1.079656
D  0.546255  0.684915 -1.946308  0.349745
E -0.468673  1.925515  0.338926  0.915947

In [77]:
lod = 0.001

df[df > lod].count(axis=1)

A    3
B    3
C    3
D    3
E    3
dtype: int64

In [79]:
# logicki operatori
# & (AND)
# | (OR) alt gr + W
# ~ (NOT) alt gr + 1

df[(df['W'] > 0) | (df['Y'] > 0)]

W         X         Y         Z
A  0.432646 -1.293831  0.777318  2.366005
B  0.395894  1.835238  0.112152 -1.323530
C  0.213568  1.551675  2.147714 -1.079656